# build environment
FROM node:14-alpine as build
RUN apk update && apk add git
WORKDIR /app
ENV PATH /app/node_modules/.bin:$PATH
COPY package.json ./
COPY yarn.lock ./
RUN yarn 
COPY . ./
RUN apk update && apk add git
RUN yarn build

# production environment
FROM nginx:stable-alpine
COPY ./nginx.conf /etc/nginx/conf.d/default.conf
COPY --from=build /app/build /usr/share/nginx/html
EXPOSE 3002
CMD ["nginx", "-g", "daemon off;"]